# Generated by Django 4.0.4 on 2022-05-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModeName', models.CharField(max_length=50, verbose_name='ModeName:')),
                ('IWater', models.IntegerField(verbose_name='Watering Interval:')),
                ('TWater', models.IntegerField(verbose_name='Watering Time:')),
                ('ILight', models.IntegerField(verbose_name='Lighting Interval:')),
                ('TLight', models.IntegerField(verbose_name='Lighting Time:')),
                ('Temperature', models.IntegerField(verbose_name='Temperature:')),
                ('Humidity', models.IntegerField(verbose_name='Humidity:')),
                ('GrowingTime', models.DurationField(verbose_name='GrowingTime:')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FarmName', models.CharField(max_length=50, verbose_name='Farm name:')),
                ('MacAddress', models.CharField(max_length=17, verbose_name='Mac Address:')),
                ('Temperature', models.IntegerField(verbose_name='Temperature:')),
                ('Humidity', models.IntegerField(verbose_name='Humidity:')),
                ('TimeTarget', models.DateTimeField(verbose_name='Time Target:')),
                ('TimeLeft', models.CharField(max_length=50, verbose_name='Time Left:')),
                ('GrowthProcess', models.IntegerField(verbose_name='Growth Process:')),
                ('CheckLine', models.BooleanField(default=False, verbose_name='Online:')),
                ('TimeDelta', models.DateTimeField(verbose_name='TimePass:')),
                ('AvailabilityOfWater', models.BooleanField(default=False, verbose_name='Availability of water')),
                ('Mode', models.CharField(max_length=50, verbose_name='Mode:')),
                ('Working', models.BooleanField(default=False, verbose_name='Working:')),
            ],
        ),
    ]
