# Generated by Django 4.1.dev20220406104243 on 2022-04-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FarmName', models.CharField(blank=True, max_length=50, verbose_name='Farm name:')),
                ('Temperature', models.FloatField(verbose_name='Temperature:')),
                ('Humidity', models.IntegerField(verbose_name='Humidity:')),
                ('Light', models.IntegerField(verbose_name='Light:')),
                ('TimeLeft', models.DateTimeField(verbose_name='Time Left:')),
                ('GrowthProcess', models.IntegerField(verbose_name='Growth Process:')),
            ],
        ),
    ]
