# Generated by Django 4.1.dev20220406104243 on 2022-05-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModName', models.CharField(max_length=50, verbose_name='ModName:')),
                ('IWater', models.IntegerField(verbose_name='Watering Interval:')),
                ('TWater', models.IntegerField(verbose_name='Watering Time:')),
                ('ILight', models.IntegerField(verbose_name='Lighting Interval:')),
                ('TLight', models.IntegerField(verbose_name='Lighting Time:')),
                ('Temperature', models.IntegerField(verbose_name='Temperature:')),
                ('Humidity', models.IntegerField(verbose_name='Humidity:')),
            ],
        ),
        migrations.AlterField(
            model_name='status',
            name='FarmName',
            field=models.CharField(max_length=50, verbose_name='Farm name:'),
        ),
    ]
