# Generated by Django 4.1.dev20220406104243 on 2022-04-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='TimeDelta',
            field=models.CharField(max_length=50, verbose_name='TimePass:'),
        ),
    ]
