# Generated by Django 4.1.dev20220406104243 on 2022-04-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='CheckLine',
            field=models.BooleanField(default=False, verbose_name='Online:'),
        ),
    ]
