# Generated by Django 4.1.dev20220406104243 on 2022-04-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='GrowthProcess',
            field=models.IntegerField(default=0, verbose_name='Growth Process:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='TimeLeft',
            field=models.IntegerField(default=1, verbose_name='Time Left:'),
            preserve_default=False,
        ),
    ]
