# Generated by Django 4.1.dev20220406104243 on 2022-05-07 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mod_alter_status_farmname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mod',
            new_name='Mode',
        ),
    ]
