# Generated by Django 4.1.dev20220406104243 on 2022-04-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_status_checkline'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='MacAddress',
            field=models.CharField(default=120, max_length=17, verbose_name='Mac Address:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status',
            name='Temperature',
            field=models.IntegerField(verbose_name='Temperature:'),
        ),
    ]
