# Generated by Django 4.0.4 on 2022-05-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_mode_growingtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='Working',
        ),
    ]
