# Generated by Django 4.0.4 on 2022-05-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_status_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='ILight',
            field=models.DurationField(default='00:00:00', verbose_name='Lighting Interval:'),
        ),
        migrations.AlterField(
            model_name='mode',
            name='IWater',
            field=models.DurationField(default='00:00:00', verbose_name='Watering Interval:'),
        ),
        migrations.AlterField(
            model_name='mode',
            name='TLight',
            field=models.DurationField(default='00:00:00', verbose_name='Lighting Time:'),
        ),
        migrations.AlterField(
            model_name='mode',
            name='TWater',
            field=models.DurationField(default='00:00:00', verbose_name='Watering Time:'),
        ),
    ]
