# Generated by Django 4.0.4 on 2022-05-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_mode_ilight_alter_mode_iwater_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='Light',
            field=models.IntegerField(default=1, verbose_name='Light'),
            preserve_default=False,
        ),
    ]
