# Generated by Django 4.1.dev20220406104243 on 2022-05-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_status_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='Working',
            field=models.BooleanField(default=False, verbose_name='Working:'),
        ),
    ]
