# Generated by Django 4.0.4 on 2022-07-29 18:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_status_light'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoolerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0, verbose_name='Value:'), size=30)),
            ],
        ),
        migrations.CreateModel(
            name='LightStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0, verbose_name='Value:'), size=30)),
            ],
        ),
        migrations.CreateModel(
            name='PumpStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0, verbose_name='Value:'), size=30)),
            ],
        ),
    ]
