# Generated by Django 4.0.4 on 2022-05-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_status_working'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mode',
            name='ModName',
        ),
        migrations.AddField(
            model_name='mode',
            name='ModeName',
            field=models.CharField(default=1, max_length=50, verbose_name='ModeName:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='AvailabilityOfWater',
            field=models.BooleanField(default=False, verbose_name='Availability of water'),
        ),
    ]
