# Generated by Django 4.1 on 2022-11-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='Humidity_arrow',
            field=models.IntegerField(default=0, verbose_name='Arrow on the humidity:'),
        ),
        migrations.AddField(
            model_name='cell',
            name='Temperature_arrow',
            field=models.IntegerField(default=0, verbose_name='Arrow on the temperature:'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='Light',
            field=models.BooleanField(verbose_name='Light:'),
        ),
    ]
