# Generated by Django 4.1 on 2022-12-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_cell_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mode',
            name='IsNode',
            field=models.BooleanField(default=False, verbose_name='Is node:'),
        ),
        migrations.AddField(
            model_name='mode',
            name='NextId',
            field=models.IntegerField(default=-1, verbose_name='Next mode id:'),
        ),
    ]
